# Generated by Django 2.1.1 on 2018-10-29 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stanovanje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oglas',
            name='datum_odjava',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 28, 21, 7, 17, 283255)),
        ),
    ]
